# Generated by Django 2.2.5 on 2020-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmovie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фільм', 'verbose_name_plural': 'Фільми'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.CharField(max_length=600, verbose_name='Постер до фільму'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Силка на трейлер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(max_length=50, verbose_name='ID IMDB'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='text',
            field=models.TextField(db_index=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Назва фільму'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=6, verbose_name='Рік виходу'),
        ),
    ]
